import React from "react";

export default function ElementorStylesheets() {
	return (
		<>
			<link
				rel='stylesheet'
				id='elementor-icons-shared-0-css-css'
				href='https://bangkok.ge/wp-content/plugins/elementor/assets//lib/font-awesome/css/fontawesome.min.css'
				type='text/css'
				media='all'
			/>
			<link
				rel='stylesheet'
				id='elementor-icons-fa-solid-css-css'
				href='https://bangkok.ge/wp-content/plugins/elementor/assets//lib/font-awesome/css/solid.min.css'
				type='text/css'
				media='all'
			/>
			<link
				rel='stylesheet'
				id='themify-icons-css'
				href='https://bangkok.ge/wp-content/themes/grandrestaurant/css/themify-icons.css'
				type='text/css'
				media='all'
			/>
			<link
				rel='stylesheet'
				id='child_theme-css'
				href='https://bangkok.ge/wp-content/themes/grandrestaurant-child/style.css'
				type='text/css'
				media='all'
			/>
			<link
				rel='stylesheet'
				id='elementor-icons-css'
				href='https://bangkok.ge/wp-content/plugins/elementor/assets/lib/eicons/css/elementor-icons.min.css'
				type='text/css'
				media='all'
			/>
			<link
				rel='stylesheet'
				id='elementor-frontend-css'
				href='https://bangkok.ge/wp-content/plugins/elementor/assets/css/frontend.min.css'
				type='text/css'
				media='all'
			/>
			<link
				rel='stylesheet'
				id='elementor-post-6-css'
				href='https://bangkok.ge/wp-content/uploads/elementor/css/post-6.css'
				type='text/css'
				media='all'
			/>
			<link
				rel='stylesheet'
				id='swiper-css'
				href='https://bangkok.ge/wp-content/plugins/elementor/assets/lib/swiper/v8/css/swiper.min.css'
				type='text/css'
				media='all'
			/>
			<link
				rel='stylesheet'
				id='animatedheadline-css'
				href='https://bangkok.ge/wp-content/plugins/grandrestaurant-elementor/assets/css/animatedheadline.css'
				type='text/css'
				media='all'
			/>
			<link
				rel='stylesheet'
				id='justifiedGallery-css'
				href='https://bangkok.ge/wp-content/plugins/grandrestaurant-elementor/assets/css/justifiedGallery.css'
				type='text/css'
				media='all'
			/>
			<link
				rel='stylesheet'
				id='flickity-css'
				href='https://bangkok.ge/wp-content/plugins/grandrestaurant-elementor/assets/css/flickity.css'
				type='text/css'
				media='all'
			/>
			<link
				rel='stylesheet'
				id='owl-carousel-theme-css'
				href='https://bangkok.ge/wp-content/plugins/grandrestaurant-elementor/assets/css/owl.theme.default.min.css'
				type='text/css'
				media='all'
			/>
			<link
				rel='stylesheet'
				id='switchery-css'
				href='https://bangkok.ge/wp-content/plugins/grandrestaurant-elementor/assets/css/switchery.css'
				type='text/css'
				media='all'
			/>
			<link
				rel='stylesheet'
				id='grandrestaurant-elementor-css'
				href='https://bangkok.ge/wp-content/plugins/grandrestaurant-elementor/assets/css/grandrestaurant-elementor.css'
				type='text/css'
				media='all'
			/>
			<link
				rel='stylesheet'
				id='grandrestaurant-elementor-responsive-css'
				href='https://bangkok.ge/wp-content/plugins/grandrestaurant-elementor/assets/css/grandrestaurant-elementor-responsive.css'
				type='text/css'
				media='all'
			/>
			<link
				rel='stylesheet'
				id='elementor-post-6949-css'
				href='https://bangkok.ge/wp-content/uploads/elementor/css/post-6949.css'
				type='text/css'
				media='all'
			/>
			<link
				rel='stylesheet'
				id='responsive-css'
				href='https://bangkok.ge/wp-content/themes/grandrestaurant/css/grid.css'
				type='text/css'
				media='all'
			/>
			<link
				rel='stylesheet'
				id='grandrestaurant-custom-css-css'
				href='https://bangkok.ge/wp-content/themes/grandrestaurant/templates/custom-css.php'
				type='text/css'
				media='all'
			/>
		</>
	);
}
