import React from "react";

const Stylesheets = () => (
	<>
		<link
			rel='stylesheet'
			href='https://bangkok.ge/wp-content/plugins/elementor/assets//lib/font-awesome/css/fontawesome.min.css'
			type='text/css'
			media='all'
		/>
		<link
			rel='stylesheet'
			href='https://bangkok.ge/wp-content/plugins/elementor/assets//lib/font-awesome/css/solid.min.css'
			type='text/css'
			media='all'
		/>
		<link
			rel='stylesheet'
			href='https://bangkok.ge/wp-content/themes/grandrestaurant/css/themify-icons.css'
			type='text/css'
			media='all'
		/>
		<link
			rel='stylesheet'
			href='https://bangkok.ge/wp-content/themes/grandrestaurant-child/style.css'
			type='text/css'
			media='all'
		/>
		<link
			rel='stylesheet'
			href='https://bangkok.ge/wp-content/plugins/elementor/assets/lib/eicons/css/elementor-icons.min.css'
			type='text/css'
			media='all'
		/>
		<link
			rel='stylesheet'
			href='https://bangkok.ge/wp-content/plugins/elementor/assets/css/frontend.min.css'
			type='text/css'
			media='all'
		/>
		<link
			rel='stylesheet'
			href='https://bangkok.ge/wp-content/uploads/elementor/css/post-6.css'
			type='text/css'
			media='all'
		/>
		<link
			rel='stylesheet'
			href='https://bangkok.ge/wp-content/plugins/elementor/assets/lib/swiper/v8/css/swiper.min.css'
			type='text/css'
			media='all'
		/>
		<link
			rel='stylesheet'
			href='https://bangkok.ge/wp-content/plugins/grandrestaurant-elementor/assets/css/animatedheadline.css'
			type='text/css'
			media='all'
		/>
	</>
);

export default Stylesheets;
